apiVersion: chaos.atomix.io/v1alpha1
kind: ChaosMonkey
metadata:
  name: crash-container
spec:
  rateSeconds: 60
  jitter: .5
  selector:
    matchPods:
      - raft-group-0
      - raft-group-1
      - raft-group-2
  crash:
    crashStrategy:
      type: Container
