{{- if .Values.crd.enabled }}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: chaosmonkeys.chaos.atomix.io
spec:
  group: chaos.atomix.io
  names:
    kind: ChaosMonkey
    listKind: ChaosMonkeyList
    plural: chaosmonkeys
    singular: chaosmonkey
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
{{- end }}