{{- if .Values.crd.enabled }}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: crashes.chaos.atomix.io
spec:
  group: chaos.atomix.io
  names:
    kind: Crash
    listKind: CrashList
    plural: crashes
    singular: crash
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
{{- end }}