apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "fullname" . }}-worker
  chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  release: "{{ .Release.Name }}"
  heritage: "{{ .Release.Service }}"
spec:
  selector:
    matchLabels:
      name: {{ template "fullname" . }}-worker
  template:
    metadata:
      labels:
        name: {{ template "fullname" . }}-worker
    spec:
      serviceAccountName: {{ template "fullname" . }}
      securityContext:
        fsGroup: 999
        privileged: true
      hostNetwork: true
      containers:
        - name: {{ .Chart.Name }}-worker
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          command:
          - chaos-worker
          readinessProbe:
            exec:
              command:
                - stat
                - /tmp/operator-sdk-ready
            initialDelaySeconds: 4
            periodSeconds: 10
            failureThreshold: 1
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: OPERATOR_NAME
              value: "{{ template "fullname" . }}"
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
