{{- if .Values.crd.enabled }}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: stresses.chaos.atomix.io
spec:
  group: chaos.atomix.io
  names:
    kind: Stress
    listKind: StressList
    plural: stresses
    singular: stress
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
{{- end }}