apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaos-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      name: chaos-controller
  template:
    metadata:
      labels:
        name: chaos-controller
    spec:
      serviceAccountName: chaos-controller
      containers:
        - name: chaos-controller
          # Replace this with the built image name
          image: atomix/chaos-controller
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - chaos-controller
          imagePullPolicy: Always
          readinessProbe:
            exec:
              command:
                - stat
                - /tmp/operator-sdk-ready
            initialDelaySeconds: 4
            periodSeconds: 10
            failureThreshold: 1
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "chaos-controller"
