apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: chaos-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      name: chaos-worker
  template:
    metadata:
      labels:
        name: chaos-worker
    spec:
      serviceAccountName: chaos-controller
      securityContext:
        fsGroup: 999
        privileged: true
      hostNetwork: true
      containers:
        - name: chaos-worker
          # Replace this with the built image name
          image: atomix/chaos-worker
          command:
          - chaos-worker
          imagePullPolicy: Always
          readinessProbe:
            exec:
              command:
                - stat
                - /tmp/operator-sdk-ready
            initialDelaySeconds: 4
            periodSeconds: 10
            failureThreshold: 1
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: OPERATOR_NAME
              value: "chaos-worker"
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
