nameOverride: ""

crd:
  enabled: true

controller:
  replicas: 1
  image:
    repository: atomix/chaos-controller
    tag: latest
    pullPolicy: IfNotPresent
    pullSecrets: []
  resources:
    requests:
      cpu: 0.5
      memory: 512Mi

worker:
  replicas: 1
  image:
    repository: atomix/chaos-worker
    tag: latest
    pullPolicy: IfNotPresent
    pullSecrets: []
  resources:
    requests:
      cpu: 0.5
      memory: 512Mi